services:
  gateway-1:
    image: matheusprotzen/gateways-mock:latest
    container_name: betalent-gateway-1
    ports:
      - '3001:3001'
    networks:
      - backend
  gateway-2:
    image: matheusprotzen/gateways-mock:latest
    container_name: betalent-gateway-2
    ports:
      - '3002:3002'
    networks:
      - backend
  db:
    image: mysql:latest
    container_name: betalent-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: betalent
      MYSQL_DATABASE: betalent
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  adonis:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: betalent-adonis
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    networks:
      - backend
    profiles:
      - production

networks:
  backend:
    driver: bridge
