name: adonisjs-ci-test-workflow
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  adonisjs-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    container:
      image: node:${{ matrix.node-version }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: adonis
          MYSQL_DATABASE: adonis
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run migrations & seeds
        run: npm run migrations:fresh
        env:
          APP_KEY: 8888X_gsMas98f5W76IDlmxjQ6_f8798
          NODE_ENV: test
          DB_HOST: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: adonis
          DB_DATABASE: adonis

      - name: Run tests
        run: node ace test
        env:
          APP_KEY: 8889X_gsMas98f5W76IDlmxjQ6_f8798
          NODE_ENV: test
          DB_HOST: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: adonis
          DB_DATABASE: adonis
